In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F

import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
print(torch.__version__)

1.10.0+cu111


In [3]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [4]:
type(arr),arr.dtype

(numpy.ndarray, dtype('int64'))

In [5]:
x = torch.from_numpy(arr)
type(x),x.dtype

(torch.Tensor, torch.int64)

In [6]:
y = torch.as_tensor(arr)
type(y),y.dtype

(torch.Tensor, torch.int64)

In [7]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4,3)
arr2d.shape

(4, 3)

In [8]:
x2 = torch.from_numpy(arr2d)
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [9]:
arr 

array([1, 2, 3, 4, 5])

In [10]:
x

tensor([1, 2, 3, 4, 5])

In [11]:
# tensor.as_tensor(),tensor.from_numpy(), ...
arr[0] = 99
arr,x,y

(array([99,  2,  3,  4,  5]),
 tensor([99,  2,  3,  4,  5]),
 tensor([99,  2,  3,  4,  5]))

In [12]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
tensor1 = torch.tensor(my_arr)
tensor2 = torch.from_numpy(my_arr)
tensor3 = torch.as_tensor(my_arr)
tensor4 = torch.Tensor(my_arr)
my_arr[0] = 999

my_arr, tensor1,tensor2,tensor3,tensor4

(array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [14]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int64')

In [15]:
torch.tensor(new_arr).dtype

torch.int64

In [16]:
my_tensor = torch.Tensor(new_arr)
my_tensor.dtype

torch.float32

In [17]:
my_tensor = torch.FloatTensor(new_arr)
my_tensor.dtype

torch.float32

----

In [18]:
torch.empty(4,2)

tensor([[4.6529e-12, 3.0932e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30]])

In [19]:
torch.zeros(4,3,dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [20]:
torch.ones(4,3)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [22]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [23]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [24]:
# Değişti !!!
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [25]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [26]:
torch.rand(4,3).max(),torch.rand(4,3).min()

(tensor(0.9097), tensor(0.0358))

In [27]:
torch.randn(4,3).mean(),torch.randn(4,3,).std()

(tensor(-0.7708), tensor(0.8315))

In [28]:
torch.rand(4,3)

tensor([[0.2955, 0.0477, 0.8147],
        [0.5149, 0.7782, 0.2511],
        [0.8737, 0.9120, 0.0968],
        [0.1933, 0.5641, 0.3545]])

In [29]:
torch.randn(3,4)

tensor([[ 0.3623, -0.4395, -1.1559,  0.7516],
        [-0.5001,  0.7589, -0.2593, -0.5712],
        [ 0.2898, -1.2892,  0.4874,  0.3820]])

In [30]:
# High Exclusive

torch.randint(low = 0, high = 11, size = (5,5))

tensor([[ 6,  1,  5, 10,  4],
        [ 8,  4,  2,  8,  1],
        [ 6,  9, 10,  7,  1],
        [ 4,  8,  0,  1,  2],
        [ 9,  8,  1,  3,  7]])

In [31]:
x = torch.zeros(2,5)
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [32]:
x.shape,x.size

(torch.Size([2, 5]), <function Tensor.size>)

In [33]:
torch.rand_like(x)

tensor([[0.2329, 0.4323, 0.0957, 0.7891, 0.7945],
        [0.0473, 0.7877, 0.2144, 0.6294, 0.3061]])

In [34]:
torch.randn_like(x)

tensor([[ 1.1678,  0.5189,  0.0504, -0.2470, -0.3240],
        [ 0.8699, -2.3887, -0.0216,  1.1356,  0.9781]])

In [35]:
torch.randint_like(x, low = 0, high = 11)

tensor([[7., 5., 2., 7., 0.],
        [4., 5., 4., 7., 6.]])

In [36]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [37]:
torch.rand(2,3)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

---

In [38]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [39]:
x[:,1],x[1,1]

(tensor([1, 3, 5]), tensor(3))

In [40]:
# Farka dikkat
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [41]:
x[:,1]

tensor([1, 3, 5])

In [42]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [44]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [45]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
z = x.view(2,5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [47]:
t = x.reshape(2,5)
t

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [48]:
x[0] = 9999
x,t,z

(tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9]),
 tensor([[9999,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9]]),
 tensor([[9999,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9]]))

In [49]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x.view(2,-1)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [51]:
a = torch.tensor([1.,2.,3.])
a

tensor([1., 2., 3.])

In [52]:
b = torch.tensor([4.,5.,6.])
b

tensor([4., 5., 6.])

In [53]:
a + b

tensor([5., 7., 9.])

In [54]:
torch.add(a,b)

tensor([5., 7., 9.])

In [55]:
# a = a + b
a.add_(b)


tensor([5., 7., 9.])

In [56]:
# a = a * b
a.mul_(b)

tensor([20., 35., 54.])

In [57]:
a,b

(tensor([20., 35., 54.]), tensor([4., 5., 6.]))

In [58]:
a.mul(b)

tensor([ 80., 175., 324.])

In [59]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [60]:
a.dot(b)

tensor(32.)

In [61]:
a.mul(b)

tensor([ 4., 10., 18.])

In [62]:
a@b

tensor(32.)

In [63]:
x = torch.arange(0,10).reshape(2,5)
y = x.reshape(5,2)

x @ y

tensor([[ 60,  70],
        [160, 195]])

In [64]:
x = torch.tensor([2.,3.,4.,5.])
x

tensor([2., 3., 4., 5.])

In [66]:
# (2**2 + 3 **2 + 4**2 + 5**2 ) ** 1/2
x.norm()

tensor(7.3485)

In [67]:
x.numel()

4