In [1]:
import torch
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

from google.colab import drive
from google.colab.patches import cv2_imshow

drive.mount("/content/drive")

Mounted at /content/drive


In [2]:
print(torch.__version__)

1.10.0+cu111


# Tensor Basics

In [3]:
arr = np.array([1,2,3,4,5])
arr.dtype,type(arr)

(dtype('int64'), numpy.ndarray)

In [4]:
torch.from_numpy(arr).dtype,torch.as_tensor(arr).dtype, torch.from_numpy(arr)

(torch.int64, torch.int64, tensor([1, 2, 3, 4, 5]))

In [5]:
x1 = torch.as_tensor(arr)
type(x1)

torch.Tensor

In [6]:
x1

tensor([1, 2, 3, 4, 5])

In [7]:
arr2d = np.arange(0.0,12.0)
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [8]:
x2 = torch.from_numpy(arr2d)
x2.dtype

torch.float64

In [9]:
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [10]:
print(arr)
arr[0] = 99
print(arr)

[1 2 3 4 5]
[99  2  3  4  5]


In [11]:
# Tensor değişiklik oldu !!!
x1

tensor([99,  2,  3,  4,  5])

In [12]:
my_arr =np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
my_arr[0] = 999
my_arr

array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
my_other_tensor

tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
# Buradaki farka çok dikkat Biri "from_numpy" biri "tensor" den oluşma ama from_nummpy gelme olan değişiyor !!!

my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# Başka bir örnekle bakalım !!!

exp_arr = np.arange(0,10)
exp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
tensor1 = torch.as_tensor(exp_arr)
tensor2 = torch.from_numpy(exp_arr)
tensor3 = torch.tensor(exp_arr)

In [20]:
exp_arr[0] = 99
tensor1,tensor2,tensor3

(tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [21]:
tensor1.dtype,tensor2.dtype,tensor2.dtype,exp_arr.dtype

(torch.int64, torch.int64, torch.int64, dtype('int64'))

--

In [22]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int64')

In [23]:
my_tensor1 = torch.tensor(new_arr)
my_tensor1.dtype

torch.int64

In [24]:
# Fark olarak !! 
# Float Değer taşıması !!

my_tensor2 = torch.Tensor(new_arr)
my_tensor2.dtype

torch.float32

In [25]:
my_tensor3 = torch.FloatTensor(new_arr)
my_tensor3.dtype

torch.float32

In [26]:
new_arr[0] = 99
my_tensor1,my_tensor2,my_tensor3,new_arr

(tensor([1, 2, 3]),
 tensor([1., 2., 3.]),
 tensor([1., 2., 3.]),
 array([99,  2,  3]))

In [27]:
torch.empty((2,2))

tensor([[-1.6845e+14,  3.0917e-41],
        [ 3.3631e-44,  0.0000e+00]])

In [28]:
torch.zeros((4,3),dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [29]:
torch.ones((4,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [30]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [31]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [32]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [33]:
torch.tensor([1,2,3])

tensor([1, 2, 3])

In [34]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [35]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [36]:
# Uniform Distribution!!!

torch.rand((4,3))

tensor([[0.7017, 0.5724, 0.4706],
        [0.4361, 0.8151, 0.9698],
        [0.0973, 0.7821, 0.2312],
        [0.0636, 0.9560, 0.5534]])

In [37]:
torch.randn((4,3))

tensor([[-0.8036, -0.8425, -0.9916],
        [-0.4767, -0.0434, -1.1032],
        [-0.4464,  0.7053, -0.4213],
        [ 1.4973,  0.3386,  1.3531]])

In [38]:
# high number exclusive !!!

torch.randint(low = 0, high = 10 , size = (5,5))

tensor([[0, 5, 9, 3, 3],
        [2, 1, 3, 9, 9],
        [5, 5, 1, 9, 6],
        [9, 7, 5, 7, 6],
        [9, 6, 6, 1, 9]])

In [39]:
x = torch.zeros((2,5))
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [40]:
x.shape

torch.Size([2, 5])

In [41]:
torch.rand_like(x)

tensor([[0.0857, 0.4187, 0.6293, 0.9108, 0.6002],
        [0.0731, 0.0129, 0.3667, 0.5076, 0.1304]])

In [42]:
torch.randn_like(x)

tensor([[ 1.2166, -1.0912,  0.0387,  0.7670, -0.4783],
        [ 0.1042,  0.7851, -1.2815, -0.8444,  0.6040]])

In [43]:
torch.randint_like(x, low = 0, high = 11)

tensor([[ 6.,  2.,  0.,  3.,  7.],
        [10.,  8.,  9.,  2.,  9.]])

In [44]:
torch.manual_seed(42)
torch.rand((2,3))

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [45]:
torch.rand((2,3))

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

# Tensor Operations

In [46]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [47]:
x[1,1]

tensor(3)

In [48]:
x[:,1]

tensor([1, 3, 5])

In [49]:
type(x[1,1])

torch.Tensor

In [50]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [51]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [53]:
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x.reshape((2,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [55]:
x = torch.arange(10)
x.shape

torch.Size([10])

In [56]:
x.view((2,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [57]:
z = x.view((2,5))
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [58]:
x[0] = 9999
x,z

(tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9]),
 tensor([[9999,    1,    2,    3,    4],
         [   5,    6,    7,    8,    9]]))

In [59]:
x.shape,z.shape

(torch.Size([10]), torch.Size([2, 5]))

In [60]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
x.shape

torch.Size([10])

In [62]:
x.view((2,-1))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [63]:
x.view((-1,5))

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [64]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [65]:
a.dtype,b.dtype

(torch.float32, torch.float32)

In [66]:
a+b

tensor([5., 7., 9.])

In [67]:
torch.add(a,b)

tensor([5., 7., 9.])

In [68]:
a.mul(b)

tensor([ 4., 10., 18.])

In [69]:
a

tensor([1., 2., 3.])

In [70]:
# Buradaki farka bak !!!
# a = a * b

a.mul_(b)

tensor([ 4., 10., 18.])

In [71]:
a

tensor([ 4., 10., 18.])

In [72]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [73]:
a.mul(b)

tensor([ 4., 10., 18.])

In [74]:
a.dot(b)

tensor(32.)

In [75]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [76]:
b = torch.tensor([[6,7],[8,9],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  9],
        [10, 11]])

In [77]:
a.shape,b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [78]:
torch.mm(a,b)

tensor([[56, 62],
        [80, 89]])

In [79]:
# Aynı şey !!!

a @ b

tensor([[56, 62],
        [80, 89]])

In [80]:
x = torch.tensor([1.,2.,3.,4.,5.])
x.norm()

tensor(7.4162)

In [81]:
x.numel()

5

In [82]:
len(x)

5

In [83]:
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [84]:
len(a),a.numel()

(2, 6)