In [ ]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

1.10.0+cu111


In [ ]:
arr = np.array([1,2,3,4,5])
arr.dtype, type(arr)

(dtype('int64'), numpy.ndarray)

In [ ]:
torch.from_numpy(arr).dtype, torch.as_tensor(arr).dtype, torch.from_numpy(arr)

(torch.int64, torch.int64, tensor([1, 2, 3, 4, 5]))

In [ ]:
x1 = torch.as_tensor(arr)
type(x1)

torch.Tensor

In [ ]:
x1

tensor([1, 2, 3, 4, 5])

In [ ]:
arr2d = np.arange(0.0, 12.0)
arr2d = arr2d.reshape(4,3)
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [ ]:
# x1'e tensor olarak atadık !!!
print(arr)
print()
arr[0] = 99
print(arr)

[1 2 3 4 5]

[99  2  3  4  5]


In [ ]:
# Tensorde de değişiklik oldu !!!
x1

tensor([99,  2,  3,  4,  5])

In [ ]:
my_arr = np.arange(0,10)
my_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_tensor = torch.tensor(my_arr)
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
my_other_tensor = torch.from_numpy(my_arr)
my_other_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# torch.tensor() olanda değişiklik olmadı !!!
# Buradaki farka çok dikkat Biri "from_numpy" biri "tensor" den oluşma ama from_nummpy gelme olan değişiyor !!!

my_arr[0] = 999
my_arr,my_tensor,my_other_tensor

(array([999,   1,   2,   3,   4,   5,   6,   7,   8,   9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([999,   1,   2,   3,   4,   5,   6,   7,   8,   9]))

In [ ]:
# Başka bir örnekle bakalım !!!

exp_arr = np.arange(0, 10)
exp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
tensor1 = torch.as_tensor(exp_arr)
tensor2 = torch.tensor(exp_arr)
tensor3 = torch.from_numpy(exp_arr)

exp_arr[0] = 99

tensor1,tensor2,tensor3

(tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 tensor([99,  1,  2,  3,  4,  5,  6,  7,  8,  9]))

In [ ]:
tensor1.dtype,tensor2.dtype,tensor3.dtype

(torch.int64, torch.int64, torch.int64)

---

In [ ]:
new_arr = np.array([1,2,3])
new_arr.dtype

dtype('int64')

In [ ]:
# Fark olarak Float Değer taşıyor !!!
# tensor -- > int 
# Tensor -- > float

my_tensor1 = torch.tensor(new_arr)
my_tensor2 = torch.Tensor(new_arr)

my_tensor1.dtype, my_tensor2.dtype

(torch.int64, torch.float32)

In [ ]:
my_tensor3 = torch.FloatTensor(new_arr)
my_tensor3.dtype

torch.float32

In [ ]:
new_arr[0] = 99

my_tensor1,my_tensor2,my_tensor3,new_arr

(tensor([1, 2, 3]),
 tensor([1., 2., 3.]),
 tensor([1., 2., 3.]),
 array([99,  2,  3]))

In [ ]:
torch.empty((2,2))

tensor([[3.7414e-06, 3.0642e-41],
        [3.3631e-44, 0.0000e+00]])

In [ ]:
torch.zeros((4,3), dtype = torch.int32)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)

In [ ]:
torch.ones((4,3))

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
torch.arange(0,18,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16])

In [ ]:
torch.arange(0,18,2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [ ]:
torch.linspace(0,18,12).reshape(3,4)

tensor([[ 0.0000,  1.6364,  3.2727,  4.9091],
        [ 6.5455,  8.1818,  9.8182, 11.4545],
        [13.0909, 14.7273, 16.3636, 18.0000]])

In [ ]:
my_tensor = torch.tensor([1,2,3])
my_tensor.dtype

torch.int64

In [ ]:
my_tensor = my_tensor.type(torch.int32)
my_tensor.dtype

torch.int32

In [ ]:
# Uniform Distribution !!!

#torch.rand(size) returns random samples from a uniform distribution over [0, 1)

#torch.randn(size) returns samples from the "standard normal" distribution [σ = 1]
#    Unlike rand which is uniform, values closer to zero are more likely to appear.

#torch.randint(low,high,size) returns random integers from low (inclusive) to high (exclusive)

torch.rand((4,3))

tensor([[0.3058, 0.2954, 0.9881],
        [0.8563, 0.3408, 0.2488],
        [0.4490, 0.5654, 0.0457],
        [0.5196, 0.7210, 0.1874]])

In [ ]:
torch.randn((4,3))

tensor([[-0.5416,  0.0163,  0.3339],
        [ 1.0348, -0.7541,  0.3250],
        [ 0.1715,  0.8199,  0.2718],
        [ 0.7392,  0.0913,  0.1986]])

In [ ]:
# High Number Exclusive !!

torch.randint(low = 0, high = 10, size = (5,5))

tensor([[5, 0, 3, 0, 0],
        [1, 2, 8, 5, 0],
        [2, 4, 0, 6, 2],
        [9, 5, 7, 3, 7],
        [1, 8, 6, 4, 9]])

In [ ]:
x = torch.zeros((2,5))
x

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
x.shape

torch.Size([2, 5])

In [ ]:
torch.rand_like(x)

tensor([[0.7202, 0.2383, 0.0145, 0.6229, 0.6487],
        [0.7608, 0.0670, 0.5641, 0.2321, 0.3099]])

In [ ]:
torch.randn_like(x)

tensor([[-0.7687, -1.2813, -0.5384,  0.3449,  1.2102],
        [-1.6793,  1.7114,  0.5572,  0.0084, -1.7222]])

In [ ]:
torch.rand((2,3))

tensor([[0.2655, 0.3839, 0.0313],
        [0.4638, 0.0359, 0.5718]])

# Tensor Operations

In [ ]:
x = torch.arange(6).reshape(3,2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [ ]:
x[1,1]

tensor(3)

In [ ]:
x[:,1]

tensor([1, 3, 5])

In [ ]:
type(x[1,1])

torch.Tensor

In [ ]:
x[:,1:]

tensor([[1],
        [3],
        [5]])

In [ ]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.view(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x.reshape(2,5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
z = x.view((2,5))
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [ ]:
x[0] = 9999

print(x)
print()
print(z)

tensor([9999,    1,    2,    3,    4,    5,    6,    7,    8,    9])

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])


In [ ]:
x.shape, z.shape

(torch.Size([10]), torch.Size([2, 5]))

In [ ]:
x.view((2,-1))

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
x.view((-1,5))

tensor([[9999,    1,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [ ]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

a.dtype, b.dtype

(torch.float32, torch.float32)

In [ ]:
a + b

tensor([5., 7., 9.])

In [ ]:
torch.add(a,b)

tensor([5., 7., 9.])

In [ ]:
a.mul(b)

tensor([ 4., 10., 18.])

In [ ]:
a,b

(tensor([1., 2., 3.]), tensor([4., 5., 6.]))

In [ ]:
# Buradaki farka bak !!
# a = a + b

a.mul_(b)

tensor([ 4., 10., 18.])

In [ ]:
a

tensor([ 4., 10., 18.])

In [ ]:
b

tensor([4., 5., 6.])

In [ ]:
a = torch.tensor([1.,2.,3.])
b = torch.tensor([4.,5.,6.])

In [ ]:
a.mul(b)

tensor([ 4., 10., 18.])

In [ ]:
a.dot(b)

tensor(32.)

In [ ]:
a = torch.tensor([[0,2,4],[1,3,5]])
a

tensor([[0, 2, 4],
        [1, 3, 5]])

In [ ]:
b = torch.tensor([[6,7],[8,7],[10,11]])
b

tensor([[ 6,  7],
        [ 8,  7],
        [10, 11]])

In [ ]:
a.shape, b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [ ]:
torch.mm(a,b)

tensor([[56, 58],
        [80, 83]])

In [ ]:
# Aynı şey !!!

a @ b

tensor([[56, 58],
        [80, 83]])

In [ ]:
x = torch.tensor([1.,2.,3.,4.,5.])
x

tensor([1., 2., 3., 4., 5.])

In [ ]:
x.numel()

5

In [ ]:
len(x)

5

In [ ]:
len(a), a.numel()

(2, 6)

In [93]:
# (2**2 + 5**2 + 8**2 + 14**2) ** 1/2
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)